spring.application.name=spotter
spring.main.banner-mode=off
spring.shell.interactive.enabled=true

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.secret-key=secretpassword
security.jwt.expiration-time=3600000
app.jwt.access-token-name=access_token

logging.level.org.springframework.security=DEBUG
logging.level.root=INFO

s3.endpoint=http://localhost:3900
s3.access-key=GK4447d0e312e07d19102c8c2b
s3.secret-key=01b755932b36cd8db998d8f074dbedb9ae7529c8c69c5fb9965eb0dd9822dc42
s3.region=us-east-1
app.s3-public-url=url

app.avatars-bucket-name=avatars

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

app.verification-token-expiration-time-hours=24

springdoc.swagger-ui.url=/v3/api-docs
springdoc.api-docs.path=/v3/api-docs